baseURL = "/"
languageCode = "pt-br"
title = "Cityhub"
defaultContentLanguage = "pt"
theme = "spectral"

[params]
fancyTitle = "Cityhub" # title for frontpage, may include image
#copyright = "John Doe"
description = '<b>Tudo em um só app:</b><br />Permitir <b>ajuda</b> entre moradores de um mesmo bairro, e<br /> <b>Possibilitar acionamento</b> de serviços públicos'
startbuttonText = "veja nosso plano de ação"
startbuttonLink = "/docs"
body_is_markdown = true
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/docs'
title = "Documentação"

[[params.menu.main]]
url = '/canvas'
title = "Canvas"

[params.people]
enable = true

[[params.people.feature]]
image="/img/edgard.jpeg"
title = "Edgard Van Tol Taver"
body = "Engenheiro de Software focado em tecnologias para backend. Aluno de Sistemas de Informação da USP, no quarto ano."

[[params.people.feature]]
image="img/escobar.jpeg"
title = "Felipe Munhos Escobar"
body = "Estudante de Sistemas de informação, motivado para criar novas soluções tecnológicas para o mundo"

[[params.people.feature]]
image="img/gabriel.jpg"
title = "Gabriel Braga Lagrotaria de Oliveira"
body = "Estudante de sistemas de informação e entusiasta de software livre, gosto de pensar na solução de problemas"

[[params.people.feature]]
image="img/rodrigo.jpg"
title = "Rodrigo Fernandes Gomes Vieira"
body = "Meu nome é rodrigod, busco sempre aprender outras tecnologias e gostaria de trabalhar com elas."

[[params.people.feature]]
image="img/gustavo.jpeg"
title = "Gustavo Macedo"
body = ""

